name: 'Delete Cache'
description: 'GitHub action for deleting cache with a specified key.'
author: prantlf

branding:
  icon: package
  color: red

inputs:
  key:
    description: >-
      The cache key to delete. Mandatory.
    required: true
  token:
    description: >-
      Authorization token to access the cache in the target repository.
      Either a GitHub personal access token or the GitHub workflow token. And if even that is not set, the GitHub workflow token from the action-execution context will be used as default.
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
