name: Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

permissions:
  id-token: write
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - run: echo "test" > LICENSE-linux-x64.zip
    - uses: actions/cache/save@v4
      with:
        path: LICENSE-linux-x64.zip
        key: LICENSE-linux-x64.zip-${{ github.sha }}

  release:
    permissions:
      actions: write
    needs:
      - prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: pnpm/action-setup@v6
      with:
        version: latest
        run_install: |
          - args: [--frozen-lockfile, --no-verify-store-integrity]
    - uses: actions/setup-node@v7
      with:
        node-version: 24
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'
    - run: pnpm ci
    - run: npm test
      shell: bash
    - uses: actions/cache/restore@v4
      with:
        path: LICENSE-linux-x64.zip
        key: LICENSE-linux-x64.zip-${{ github.sha }}
        fail-on-cache-miss: true
    - run: |
        if [ ! -f "LICENSE-linux-x64.zip" ]; then
          echo "LICENSE-linux-x64.zip does not exist"
          exit 1
        fi
      shell: bash
    - uses: ./
      with:
        key: LICENSE-linux-x64.zip-${{ github.sha }}
    - run: rm LICENSE-linux-x64.zip
      shell: bash
    - uses: actions/cache/restore@v4
      with:
        path: LICENSE-linux-x64.zip
        key: LICENSE-linux-x64.zip-${{ github.sha }}
        fail-on-cache-miss: false
    - run: |
        if [ -f "LICENSE-linux-x64.zip" ]; then
          echo "LICENSE-linux-x64.zip exists"
          exit 1
        fi
      shell: bash
    - uses: prantlf/publish-release-action@v1
      if: ${{ github.ref_name == 'master' }}
      with:
        no-npm-auth: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
