name: Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Simulate archive creation
      shell: bash
      run: echo "test" > LICENSE-linux-x64.zip
    - name: Put archive to cache
      uses: actions/cache/save@v3
      with:
        path: LICENSE-linux-x64.zip
        key: LICENSE-linux-x64.zip-${{ github.sha }}

  release:
    needs:
      - prepare
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org'
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: |
          - args: [--frozen-lockfile, --no-verify-store-integrity]
    - name: Build
      shell: bash
      run: npm run build
    - name: Test syntax
      shell: bash
      run: npm test
    - name: Restore archive from cache
      uses: actions/cache/restore@v3
      with:
        path: LICENSE-linux-x64.zip
        key: LICENSE-linux-x64.zip-${{ github.sha }}
        fail-on-cache-miss: true
    - name: Check archive
      shell: bash
      run: |
        if [ ! -f "LICENSE-linux-x64.zip" ]; then
          echo "LICENSE-linux-x64.zip does not exist"
          exit 1
        fi
    - name: Test action
      uses: ./
      with:
        key: LICENSE-linux-x64.zip-${{ github.sha }}
    - name: Clean archive
      shell: bash
      run: rm LICENSE-linux-x64.zip
    - name: Restore archive from cache once more
      uses: actions/cache/restore@v3
      with:
        path: LICENSE-linux-x64.zip
        key: LICENSE-linux-x64.zip-${{ github.sha }}
        fail-on-cache-miss: false
    - name: Check archive
      shell: bash
      run: |
        if [ -f "LICENSE-linux-x64.zip" ]; then
          echo "LICENSE-linux-x64.zip exists"
          exit 1
        fi
    - name: Publish
      uses: cycjimmy/semantic-release-action@v3
      with:
        branches: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
